export const increaseTime = () => ({type: 'INCREASE_TIME'})
export const decreaseTime = () => ({type: 'DECREASE_TIME'})
export const resetTime = () => ({type: 'RESET_TIME'})
export const toggleJacuzzi = () => ({type: 'TOGGLE_JACUZZI'})
export const toggleClock = () => ({type: 'TOGGLE_CLOCK'})
